### ISSUE TITLE
MHS Adaptor - Resolve issues that are preventing automated tests from successfully completing

### ISSUE THREAD

**Issue by robert-joscelyne** [nhsconnect/integration-adaptors#162]
There appears to be a dependency in the tests that requires a Windows environment for them to successfully complete. Resolve these so that the test suite can complete for the  Mac OSX and Linux platforms

**Comment by bartek-sarul** [comment]
a workaround is available https://github.com/nhsconnect/integration-adaptors/blob/develop/mhs/outbound/mhs-outbound-dev-notes.md

**Comment by bartek-sarul** [comment]
https://gpitbjss.atlassian.net/browse/NIAD-58
