### ISSUE TITLE
TECHDEBT: Logging test name affects outcome

### ISSUE THREAD

**Issue by Philip-Woods** [nhsconnect/integration-adaptors#54]
The logging test `test_correct_time_format` in `common.utilities.tests.test_logger` changes the outcome depending on the name of the test. In particular the test seems to fail when the word after the first underscore is lexographically later than the letter `L`. So for example the test name `test_jar` will pass, but `test_mat` will fail.

The test attempts to parse the logging message to check the timestamp is in the correct format, however depending on the name variance described above the test may fail to get the log message and instead just gets an empty string.

**Comment by bartek-sarul** [comment]
Most likely fixed by logger refactor in NIAD-5
https://github.com/nhsconnect/integration-adaptors/pulls?q=is%3Apr+is%3Aclosed+NIAD-5
