### ISSUE TITLE
ruby support available for gpconnect

### ISSUE THREAD

**Issue by uzaif313** [nhsconnect/integration-adaptors#94]
Hi,
I need ruby support for gpconnect rest API. do you have any idea about that?

**Comment by dshipp-bjss** [comment]
Hi @uzaif313 this isn't the right project for your request. Please contact the GP Connect team with your requirements, you can use the form here: https://digital.nhs.uk/forms/gp-connect-enquiry-form

**Comment by uzaif313** [comment]
@dshipp-bjss  Thanks for response.
